apiVersion: v2
name: fraud-detection
description: Real-time fraud detection system with Kafka, Flink, and Redis
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/ajayalluri/realtime-fraud-detection
maintainers:
  - name: Ajay Alluri
    email: ajayalluri@example.com
keywords:
  - fraud-detection
  - kafka
  - flink
  - redis
  - machine-learning
  - real-time
dependencies:
  - name: kafka
    version: "18.4.2"
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: redis
    version: "17.3.7"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: "15.18.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.44.11"
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled