apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: fraud-detection
  labels:
    app: flink
    component: jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: flink:1.18-scala_2.12-java11
        args: ["jobmanager"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob-server
        - containerPort: 8081
          name: webui
        env:
        - name: FLINK_PROPERTIES
          value: |
            jobmanager.rpc.address: flink-jobmanager-service
            taskmanager.numberOfTaskSlots: 4
            parallelism.default: 12
            jobmanager.memory.process.size: 2048m
            taskmanager.memory.process.size: 4096m
            state.backend: rocksdb
            state.checkpoints.dir: file:///tmp/flink-checkpoints
            state.savepoints.dir: file:///tmp/flink-savepoints
            execution.checkpointing.interval: 30s
            execution.checkpointing.min-pause: 5s
            execution.checkpointing.timeout: 10m
            execution.checkpointing.max-concurrent-checkpoints: 1
            restart-strategy: exponential-delay
            restart-strategy.exponential-delay.initial-backoff: 10s
            restart-strategy.exponential-delay.max-backoff: 2min
            restart-strategy.exponential-delay.backoff-multiplier: 2.0
            restart-strategy.exponential-delay.reset-backoff-threshold: 10min
            restart-strategy.exponential-delay.jitter-factor: 0.1
            metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
            metrics.reporter.prom.port: 9249
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1"
        volumeMounts:
        - name: flink-config
          mountPath: /opt/flink/conf
        - name: flink-checkpoints
          mountPath: /tmp/flink-checkpoints
        - name: flink-savepoints
          mountPath: /tmp/flink-savepoints
        - name: fraud-detection-jar
          mountPath: /opt/flink/usrlib
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: flink-config
        configMap:
          name: flink-config
      - name: flink-checkpoints
        persistentVolumeClaim:
          claimName: flink-checkpoints-pvc
      - name: flink-savepoints
        persistentVolumeClaim:
          claimName: flink-savepoints-pvc
      - name: fraud-detection-jar
        configMap:
          name: fraud-detection-jar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: fraud-detection
  labels:
    app: flink
    component: taskmanager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: flink:1.18-scala_2.12-java11
        args: ["taskmanager"]
        ports:
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query-state
        - containerPort: 9249
          name: metrics
        env:
        - name: FLINK_PROPERTIES
          value: |
            jobmanager.rpc.address: flink-jobmanager-service
            taskmanager.numberOfTaskSlots: 4
            parallelism.default: 12
            jobmanager.memory.process.size: 2048m
            taskmanager.memory.process.size: 4096m
            taskmanager.memory.framework.heap.size: 128mb
            taskmanager.memory.task.heap.size: 2048mb
            taskmanager.memory.managed.size: 1024mb
            taskmanager.memory.network.min: 64mb
            taskmanager.memory.network.max: 1gb
            state.backend: rocksdb
            state.backend.rocksdb.predefined-options: SPINNING_DISK_OPTIMIZED
            state.backend.incremental: true
            state.checkpoints.dir: file:///tmp/flink-checkpoints
            execution.checkpointing.interval: 30s
            metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
            metrics.reporter.prom.port: 9249
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "2"
        volumeMounts:
        - name: flink-config
          mountPath: /opt/flink/conf
        - name: flink-checkpoints
          mountPath: /tmp/flink-checkpoints
        - name: fraud-detection-jar
          mountPath: /opt/flink/usrlib
        - name: flink-tmp
          mountPath: /tmp
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: flink-config
        configMap:
          name: flink-config
      - name: flink-checkpoints
        persistentVolumeClaim:
          claimName: flink-checkpoints-pvc
      - name: fraud-detection-jar
        configMap:
          name: fraud-detection-jar
      - name: flink-tmp
        emptyDir:
          sizeLimit: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: fraud-detection
data:
  flink-conf.yaml: |
    # Flink configuration for fraud detection system
    
    # JobManager settings
    jobmanager.rpc.address: flink-jobmanager-service
    jobmanager.rpc.port: 6123
    jobmanager.bind-host: 0.0.0.0
    jobmanager.memory.process.size: 2048m
    jobmanager.memory.jvm-metaspace.size: 256m
    
    # TaskManager settings
    taskmanager.numberOfTaskSlots: 4
    taskmanager.bind-host: 0.0.0.0
    taskmanager.memory.process.size: 4096m
    taskmanager.memory.framework.heap.size: 128mb
    taskmanager.memory.task.heap.size: 2048mb
    taskmanager.memory.managed.size: 1024mb
    
    # Execution settings
    parallelism.default: 12
    execution.buffer-timeout: 100ms
    execution.checkpointing.interval: 30s
    execution.checkpointing.min-pause: 5s
    execution.checkpointing.timeout: 10m
    execution.checkpointing.max-concurrent-checkpoints: 1
    execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION
    
    # State backend configuration
    state.backend: rocksdb
    state.backend.rocksdb.predefined-options: SPINNING_DISK_OPTIMIZED
    state.backend.incremental: true
    state.checkpoints.dir: file:///tmp/flink-checkpoints
    state.savepoints.dir: file:///tmp/flink-savepoints
    
    # Restart strategy
    restart-strategy: exponential-delay
    restart-strategy.exponential-delay.initial-backoff: 10s
    restart-strategy.exponential-delay.max-backoff: 2min
    restart-strategy.exponential-delay.backoff-multiplier: 2.0
    restart-strategy.exponential-delay.reset-backoff-threshold: 10min
    restart-strategy.exponential-delay.jitter-factor: 0.1
    
    # Web UI
    web.port: 8081
    web.bind-address: 0.0.0.0
    web.submit.enable: true
    web.cancel.enable: true
    
    # Metrics
    metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prom.port: 9249
    metrics.scope.jm: fraud-detection.jobmanager
    metrics.scope.tm: fraud-detection.taskmanager
    metrics.scope.task: fraud-detection.task
    
    # High availability (disabled for simplicity)
    # high-availability: zookeeper
    # high-availability.zookeeper.quorum: zookeeper-service:2181
    # high-availability.storageDir: file:///tmp/flink-ha
    
    # Security (disabled for development)
    # security.ssl.enabled: false
    
    # Fraud detection specific optimizations
    taskmanager.network.memory.fraction: 0.15
    taskmanager.network.memory.min: 64mb
    taskmanager.network.memory.max: 1gb
    taskmanager.memory.network.max: 1gb
    
    # Kafka connector settings
    table.exec.source.idle-timeout: 30s
    
  log4j-console.properties: |
    # Log4j configuration for Flink in Kubernetes
    
    # Root logger
    log4j.rootLogger=INFO, console
    
    # Console appender
    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.layout=org.apache.log4j.PatternLayout
    log4j.appender.console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
    
    # Suppress excessive logging
    log4j.logger.akka=INFO
    log4j.logger.org.apache.kafka=WARN
    log4j.logger.org.apache.hadoop=WARN
    log4j.logger.org.apache.zookeeper=WARN
    log4j.logger.org.apache.flink.shaded.akka=INFO
    log4j.logger.org.apache.flink.runtime.checkpoint=INFO
    log4j.logger.org.apache.flink.runtime.executiongraph=INFO
    log4j.logger.org.apache.flink.runtime.state=INFO
    
    # Enable debug logging for fraud detection components
    log4j.logger.com.frauddetection=DEBUG
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-checkpoints-pvc
  namespace: fraud-detection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-savepoints-pvc
  namespace: fraud-detection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi